### PR TITLE
Add Canadian provinces

### PR DESCRIPTION
**Pull request by eahenke**

### CODE REVIEW

**Comment by mdb** [comment]
@eahenke Thanks! I'm on the fence on this one, given that `madison`'s stated purpose is in dealing with US state names and abbreviations, and not necessarily Canadian provinces. Does it make sense to add a `madison.canada` module, which itself has `getProvinceName` and `getProvinceAbbrev` methods?

**Comment by eahenke** [comment]
Ha, I was worried there might be some pushback on that front.  My reasoning was Canada and US share the same abbreviation system, there's no overlap of abbreviations, and being neighbors a lot of companies do business on both sides of the border (mine included).  My use case for a combined module is that we use madison for customer addresses, and depending on how they come into our system they may or may not have a populated country field, but will always have a state.  So having the combined module is easier/faster/more reliable than doing a postal code regex to determine the country, and then point to the right module (plus one fewer dependency).

**Comment by mdb** [comment]
@eahenke Wow, a real, live production user! Exciting. Given your use-case, I'd say you are more invested in `madison` than am I, so: 👍 

Thanks for taking the time to explain respond.

**Comment by eahenke** [comment]
No problem, thanks for merging!

**Pull request merged**
